name:         uniform-json 
version:      0.0.5
license:      GPL
license-file: GPL_3
maintainer:   Andrew U. Frank <frank@geoinfo.tuwien.ac.at>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     Data Text JSON YAML Pandoc
synopsis: handling of JSON and YAML in an uniform way
description: |
    remove particular aspects of abstraction in json and yaml - with an eye to use it with pandoc
    v0.0.4 for aeson >2.0
    v0.0.5 for ghc 9.2.1, aeson >= 2 

# source-repository: head
# type: git
# github: https://github.com/andrewufrank/uniform-json.git
 


extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- monads-tf
# - safe
# - text
# - bytestring
- pretty-show
- yaml
- aeson 
# for citeproc!
- lens
- lens-aeson
- aeson-pretty
- unordered-containers
- uniformBase ==0.1.3

library:
  source-dirs: 
  - src
  # verbatim:
  #   autogen-modules:
  #       Paths_uniform_json



# tests:
#   strings-test:
#     main:                Testing.hs
#     # there is a second main test file TestingJson.hs
#     source-dirs:         tests
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - HTF
#     - uniforBase ==0.1.3
#     - quickcheck-text
#     - time
#     - uniform-time
#     - uniform-json
    
