name: uniform-latex2pdf
version: 0.1.5.6
# cabal-version: >=1.22
# build-type: Simple
license: GPL
license-file: GPL_3
github:  andrewufrank/u4blog.git/uniform-latex2pdf
maintainer: Andrew U. Frank <andrewufrank@gmail.com>
author: Andrew Frank
category: PDF Latex
synopsis: convert a latex `tex` file to a pdf 
description: |
  convert a latex file to pdf 
  calling lualatex with the flags etc. necessary to include bibliography and footnotes



# source-repository head
#     type: git
#     location: https://github.com/andrewufrank/uniform-http.git

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- uniformBase >=0.1.5
- uniform-json >=0.1.5
- uniform-pandoc >=0.1.5.2
# - pandoc-highlighting-extensions
- process
- silently
- doctemplates
- doclayout
- aeson  # for generic read 

library:
  source-dirs: src


# tests:
#   webserver-test:
#     main:                Testing.hs
#     source-dirs:         tests
#     dependencies:
#     # - uniform-algebras
#     - HTF
#     - quickcheck-text
#     # - uniform-strings
#     # - uniform-http
#     - uniformBase
#     - uniform-latex2pdf
