name:         uniform-pandoc 
version:      0.0.2.1
license:      GPL
license-file: GPL_3
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     Uniformhandling of   some pandoc stuff
synopsis:   handling of   some pandoc stuff   
description: | 
  remove particular aspects of abstraction 
  0.0.2.1 for cabal may 2021 8.10.4


extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- pandoc
- pandoc-citeproc
- pandoc-types
- bibtex
- uniformBase
- uniform-json

# - uniform-fileio
# - uniform-error
- doctemplates
- doclayout
- lens 
- aeson 
- lens-aeson
- parsec
- containers
- process
# - uniform

library:
  source-dirs: 
  - .   
# the '.' finds the library in their folders with LibName

tests:
  pandoctest:
    main:                Testing.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HTF
    - uniform-pandoc
    - uniform-convenience
    # - uniformBase
    # - ReplaceUmlaut 