name: uniform-shake
version: 0.0.1.1
# cabal-version: >=1.22
# build-type: Simple
license: GPL
license-file: GPL_3
maintainer: Andrew U. Frank <andrewufrank@gmail.com>
author: Andrew Frank
category: 'Build, Uniform'
synopsis: uniform wrapper for shake 
description: |
    shake top level functions using Path (not filepath)
    version 2 to include in uniform ecosystem
    1.0 used for my homepage - fixes
    0.0.1.1 for cabal 

# source-repository head
#     type: git
#     location: https://github.com/andrewufrank/uniform-http.git

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
-  base
- shake
- uniformBase
- uniform-json

library:
  source-dirs: .


tests:
  webserver-test:
    main:                Testing.hs
    source-dirs:         tests
    dependencies:
    # - uniform-algebras
    - HTF
    - quickcheck-text
    # - uniform-strings
    # - uniform-http
    - uniformBase
    - uniform-shake

#     exposed-modules:
#             Uniform.Http
#             -- the next two must not be imported
#             -- except for testing here
#              Uniform.HttpCall
#              Uniform.HttpURI
#     exposed: True
#     buildable: True
#     default-language: Haskell2010
#     hs-source-dirs: .
#     other-modules:

# Test-Suite httpTestAuto
#     type:       exitcode-stdio-1.0
#     main-is:    Testing.hs
#     build-depends: base, HTF
#         -- , uniform-fileio
#         , uniform-strings
#         , uniform-error
#         , uniform-http
#         , uniform-json
#         -- , aeson
# --        -- needed because the two files

#             , uniform-algebras
#             , network-uri
# -- for tests
#             , HTF
#             , test-invariant
#     default-language: Haskell2010
#     hs-source-dirs: tests
#     other-modules:
#                  Uniform.HttpCall_test
#                  Uniform.HttpURI_test
# --             Uniform.HttpCall
# --             Uniform.HttpURI
