name: uniform-shake
version: 0.1.5.2
# cabal-version: >=1.22
# build-type: Simple
license: GPL
license-file: GPL_3
github:  andrewufrank/u4blog.git/uniform-shake
maintainer: Andrew U. Frank <andrewufrank@gmail.com>
author: Andrew Frank
category: 'Build, Uniform'
synopsis: uniform wrapper for shake 
description: |
    shake top level functions using Path (not filepath)
    version 2 to include in uniform ecosystem,
    i.e. use text, Path,

# source-repository head
#     type: git
#     location: https://github.com/andrewufrank/uniform-http.git

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
-  base >= 4.7 && < 5
- shake
- uniformBase >=0.1.5
- uniform-json >= 0.1.5
- filepath 
- path 
library:
  source-dirs: src

tests:
  testall:
    main: testing.hs
    source-dirs: tests

    ghc-options: 
      -threaded 
      -rtsopts 
      -with-rtsopts=-N    
    dependencies:
      - HTF
      - quickcheck-text
      # - uniform-strings
      # - uniform-http
      - uniformBase
      - uniform-shake
      # - uniform-convenience
      # - daino
      # - data-hash
      # - shake  # from error

# tests:
#   webserver-test:
#     main:                Testing.hs
#     source-dirs:         tests
#     dependencies:
#     # - uniform-algebras
#     - HTF
#     - quickcheck-text
#     # - uniform-strings
#     # - uniform-http
#     - uniformBase ==0.1.3
#     - uniform-shake

#     exposed-modules:
#             Uniform.Http
#             -- the next two must not be imported
#             -- except for testing here
#              Uniform.HttpCall
#              Uniform.HttpURI
#     exposed: True
#     buildable: True
#     default-language: Haskell2010
#     hs-source-dirs: .
#     other-modules:

# Test-Suite httpTestAuto
#     type:       exitcode-stdio-1.0
#     main-is:    Testing.hs
#     build-depends: base, HTF
#         -- , uniform-fileio
#         , uniform-strings
#         , uniform-error
#         , uniform-http
#         , uniform-json
#         -- , aeson
# --        -- needed because the two files

#             , uniform-algebras
#             , network-uri
# -- for tests
#             , HTF
#             , test-invariant
#     default-language: Haskell2010
#     hs-source-dirs: tests
#     other-modules:
#                  Uniform.HttpCall_test
#                  Uniform.HttpURI_test
# --             Uniform.HttpCall
# --             Uniform.HttpURI
