name:         uniform-pandoc 
version:      0.0.2.4
license:      GPL
license-file: GPL_3
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     Uniform handling of   some pandoc stuff
synopsis:   handling of   some pandoc stuff   
description: | 
  remove particular aspects of abstraction 
  0.0.2.1 for cabal may 2021 8.10.4
  0.0.2.2 systematic bakeOneX2y function names
  0.0.2.3 biblio-refs fixing, not yet change to citeproc-hs
            currently fixed to old version of pandoc-types 
            processPDF.hs replaced with uniform-latex2pdf
  0.0.2.4 for ghc 9.2.1 (first for 8.10.7 limits on rpi64)
            uses pandoc (and the Pandoc.Citeproc code
            not pandoc-citeproc.hs)

# cabal-version:  1.12

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- pandoc >= 2.11

- uniformBase >=0.1.3
- uniform-json >=0.0.5

- doctemplates
- doclayout  #for  html writer (both)
# - lens 
- aeson 
# - lens-aeson
# - parsec
# - containers
# - process
# - shake

library:
  source-dirs: 
  - src   
# the '.' finds the library in their folders with LibName

# tests:
#   pandoctest:
#     main:                Testing.hs
#     source-dirs:         tests
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - HTF
#     - uniform-pandoc
#     - uniform-convenience

    # - ssg
    # - uniform-convenience
    # - uniformBase
    # - ReplaceUmlaut 