name:         uniform-pandoc 
version:      0.0.2.3
license:      GPL
license-file: GPL_3
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     Uniform handling of   some pandoc stuff
synopsis:   handling of   some pandoc stuff   
description: | 
  remove particular aspects of abstraction 
  0.0.2.1 for cabal may 2021 8.10.4
  0.0.2.2 systematic bakeOneX2y function names
  0.0.2.3 biblio-refs fixing, not yet change to citeproc-hs
            currently fixed to old version of pandoc-types 
            processPDF.hs replaced with uniform-latex2pdf

# cabal-version:  1.12

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- pandoc >=0.3.10
- pandoc-citeproc # replace later with 
# - citeproc-hs >=0.3.10 -- but currently fixed to old version of pandoc-types 
- pandoc-types  
- bibtex
- uniformBase ==0.1.3
- uniform-json

# - uniform-fileio
# - uniform-error
- doctemplates
- doclayout
- lens 
- aeson 
- lens-aeson
- parsec
- containers
- process
- shake
# - uniform

library:
  source-dirs: 
  - src   
# the '.' finds the library in their folders with LibName

tests:
  pandoctest:
    main:                Testing.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HTF
    - uniform-pandoc
    - uniform-convenience

    # - ssg
    # - uniform-convenience
    # - uniformBase
    # - ReplaceUmlaut 