name:         uniform-pandoc 
version:      0.1.5.3
license:      GPL
license-file: GPL_3
github:  andrewufrank/u4blog.git/uniform-pandoc
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     Uniform handling of   some pandoc stuff
synopsis:   handling of   some pandoc stuff   
description: | 
  remove particular aspects of abstraction 


# cabal-version:  1.12

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- pandoc >= 2.11

- uniformBase >=0.1.5.1
- uniform-json >=0.1.5.2

- doctemplates
- doclayout  #for  html writer (both)
# - lens 
- aeson 
- bytestring
# - lens-aeson
# - parsec
# - containers
# - process
# - shake

library:
  source-dirs: 
  - src   
# the '.' finds the library in their folders with LibName

# tests:
#   pandoctest:
#     main:                Testing.hs
#     source-dirs:         tests
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - HTF
#     - uniform-pandoc
#     - uniform-convenience

    # - ssg
    # - uniform-convenience
    # - uniformBase
    # - ReplaceUmlaut 