name:         uniform-cmdLineArgs
version:      0.1.5.1
license:      GPL
license-file: GPL_3
github:       andrewufrank/u4blog.git/uniform-cmdLineArgs
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     CmdLineArgs
synopsis:     a convenient handling of command line arguments
description: | 
  deals with the command line arguments and fills with decent defaults

# needs cabal install HTF to load htfpp

# consider changing to use https://hackage.haskell.org/package/cmdargs-0.10.22
# from neil mitchchel

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- monads-tf
- uniformBase >=0.1.5
# - HTF
- optparse-applicative
# # - test-invariant

library:
  source-dirs: src

# this is only a library, no directly executable
# executables:
#   primo-exe:
#     main:                Testing.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - uniform-algebras

# tests:
#   strings-test:
#     main:                Testing.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - uniform-algebras
#     - HTF
#     - test-invariant
#     - quickcheck-text
#     - uniform-strings
#     - uniform-fileio
#     - uniform-cmdLineArgs
